[package]
name = "jaburepo"
version = "0.1.3" 
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
jabu-config = { path = "../jabu-config" }
ron = "0.8"
semver = "1.0"

[dev-dependencies]
tempdir = "0.3.7"
