#!/bin/perl
use strict;
use warnings;

use File::Basename;
use File::Temp qw(tempdir);
use File::Path qw(make_path);
use File::Spec::Functions 'catfile';

# Port of the server
my $PORT = 8080;

sub pprint {
    my $msg = shift;
    print "[" . basename($0) ."]: $msg\n";
}

sub initialize_repo {
    my $tmp_dir = tempdir;
    $tmp_dir =~ s/\n//g;
    pprint "Using $tmp_dir as jabu repository";

    return $tmp_dir
}

pprint "Initializing repo...";
my $tmp_dir = initialize_repo;
pprint "Starting server...";
system("RUSTFLAGS=-Awarnings cargo r -q -- --repo-path $tmp_dir --port $PORT") == 0 or die "The server has exited with code '$?'.";
