#!/bin/perl
use strict;
use warnings;

use File::Basename;
use File::Temp qw(tempdir);
use File::Path qw(make_path);
use File::Spec::Functions 'catfile';

# Port of the server
my $PORT = 8080;

sub pprint {
    my $msg = shift;
    print "[" . basename($0) ."]: $msg\n";
}

sub initialize_repo {
    my $tmp_dir = tempdir;
    $tmp_dir =~ s/\n//g;
    pprint "Using $tmp_dir as jabu repository";

    return $tmp_dir
}

pprint "Initializing repo...";
my $tmp_dir = initialize_repo;
pprint "Starting server...";
my $cargo_cmd = "cargo r -q -- --repo-path $tmp_dir --port $PORT";

if ($^O eq "Linux") {
    system("RUSTFLAGS=-Awarnings $cargo_cmd") == 0 or die "The server has exited with code '$?'.";
} else {
    $ENV{RUSTFLAGS} = "-Awarnings";
    system("$cargo_cmd") == 0 or die "The server has exited with code '$?'.";
}
